
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=USE_DB_RECOVERY_FILE_DEST VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=cdb1';

ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE=cdb1dr LGWR ASYNC VALID_FOR=(ONLINE_LOGFILE,PRIMARY_ROLE) DB_UNIQUE_NAME=cdb1dr' SCOPE=BOTH;

ALTER SYSTEM SET LOG_ARCHIVE_FORMAT='log%t_%s_%r.arc'SCOPE=SPFILE;


ALTER SYSTEM SET FAL_SERVER=cdb1dr
ALTER SYSTEM SET FAL_CLIENT=cdb1
ALTER SYSTEM SET LOG_ARCHIVE_CONFIG='DG_CONFIG=(cdb1,cdb1dr)' SCOPE=both;
ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT='AUTO' SCOPE=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_1=ENABLE;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_2=ENABLE;
ALTER SYSTEM SET LOG_ARCHIVE_FORMAT = 'log%t_%s_%r.arc' SCOPE=SPFILE;


ALTER SYSTEM SET DG_BROKER_START=TRUE;

SHUTDOWN IMMEDIATE;
STARTUP OPEN;
