ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=USE_DB_RECOVERY_FILE_DEST VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=cdb1dr';

ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE=cdb1 LGWR ASYNC VALID_FOR=(ONLINE_LOGFILE,PRIMARY_ROLE) DB_UNIQUE_NAME=cdb1' SCOPE=BOTH;

ALTER SYSTEM SET LOG_ARCHIVE_FORMAT='log%t_%s_%r.arc'SCOPE=SPFILE;

ALTER SYSTEM SET FAL_SERVER=cdb1
ALTER SYSTEM SET FAL_CLIENT=cdb1dr
ALTER SYSTEM SET LOG_ARCHIVE_CONFIG='DG_CONFIG=(cdb1dr,cdb1)' SCOPE=both;
ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT='AUTO' SCOPE=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_1=ENABLE;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_2=ENABLE;
ALTER SYSTEM SET LOG_ARCHIVE_FORMAT = 'log%t_%s_%r.arc' SCOPE=SPFILE;
ALTER SYSTEM SET DG_BROKER_START=TRUE;



CREATE SPFILE FROM PFILE='/u01/app/oracle/product/19c/db_1/dbs/initcdb1dr.ora';
SHUTDOWN IMMEDIATE;
STARTUP OPEN;
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;

